# Generated by Django 4.1.3 on 2022-12-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beds', models.PositiveIntegerField(default=0)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
