# Generated by Django 4.1.3 on 2022-12-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0004_alter_criteria_max_price_alter_criteria_min_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='max_price',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='min_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
        ),
    ]
