# Generated by Django 4.1.3 on 2022-12-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0005_alter_criteria_max_price_alter_criteria_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='max_price',
            field=models.DecimalField(decimal_places=0, default=99999999999999, max_digits=9, null=True),
        ),
    ]
