# Generated by Django 4.1.3 on 2022-12-12 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0008_likedhouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedhouses',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
