# Generated by Django 4.1.3 on 2022-12-12 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0009_alter_likedhouses_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedhouses',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
