# Generated by Django 4.1.3 on 2022-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housero', '0012_alter_likedhouses_house_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedhouses',
            name='house_id',
            field=models.IntegerField(default=141564332),
            preserve_default=False,
        ),
    ]
